spring:
  datasource:
      url: jdbc:mysql://localhost:3306/bookstore?serverTimezone=UTC&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: root
      password: 1234
      driver-class-name: com.mysql.jdbc.Driver
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
#  data:
#    elasticsearch:
#      repositories:
#        enabled: true
#      cluster-nodes: 127.0.0.1:9300
  activemq:
    user: admin
    password: admin
    broker-url: tcp://127.0.0.1:61616
  jms:
    topic-name: test-topic
    queue-name: test-queue

mybatis:
  mapper-locations: classpath*:mapper/*.xml
server:
  port: 8081
tengxun:
  accessKey: AKIDkGWjuoQoumRovItDl46rSJM8d1OU3r86
  secretKey: pNhMkriNnwqTN1OUM8cqnUw734KMIID1
  area: ap-chengdu
  bucketName: xzsd-1300208869
  path: https://xzsd-1300208869.cos.ap-chengdu.myqcloud.com